baseURL = "https://example.com"
title = "Julien Renaux's codelabs"
theme = "codelabs"
googleAnalytics = ""

[params]
  title = "Welcome to Codelabs!"
  description = "Google Developers Codelabs provide a guided, tutorial, hands-on coding experience. Most codelabs will step you through the process of building a small application, or adding a new feature to an existing application. They cover a wide range of topics such as Android Wear, Google Compute Engine, Project Tango, and Google APIs on iOS."